version: '3.8'

services:
  db:
    image: postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    container_name: postgres-db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  dev:
    container_name: nest_js_dev
    build:
      context: .
      target: development
    command: npm run start:dev
    environment: 
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - POSTGRES_SYNC=false
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  prod:
    container_name: nest_js_prod
    build:
      context: .
      target: production
    command: npm run start:prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app