version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  dev:
    container_name: nest_js_dev
    build:
      context: .
      target: development
    command: npm run start:dev
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  prod:
    container_name: nest_js_prod
    build:
      context: .
      target: production
    command: npm run start:prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app