version: '3.8'

services:
  dev:
    container_name: nest_js_dev
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  prod:
    container_name: nest_js_prod
    build:
      context: .
      target: production
    command: npm run start:prod
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app