version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  dev:
    container_name: nest_js_dev
    build:
      context: .
      target: development
    command: npm run start:dev
    environment: 
      - DB_PORT=5432
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db

  prod:
    container_name: nest_js_prod
    build:
      context: .
      target: production
    command: npm run start:prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app