name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Launch unit test
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Launch unit test
        run: npm run lint

  static-analyse:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.0
    steps:
      - uses: actions/checkout@v2
      - name: NPM Audit
        run: npm audit --audit-level none

  documentation:
    needs: [build, test, lint, static-analyse]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.13.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Generate doc
        run: npx compodoc -p tsconfig.json -n "SpaceCode | API" -d docs
